CREATE  TABLE if not exists PLAYER (
   id INTEGER NOT NULL,
   nome VARCHAR(128) NOT NULL,
   email VARCHAR(100) NOT NULL,
   telefone VARCHAR(20) NULL,
   codinome VARCHAR(50) NOT NULL,
   grupo NUMERIC(1) NOT NULL,
   PRIMARY KEY (id),
   CONSTRAINT GRUPO_CONSTR CHECK (GRUPO in (1,2))
);

CREATE SEQUENCE IF NOT EXISTS PLAYER_SEQ START WITH 1 INCREMENT BY 1;